version: "3"
networks:
  base:
    ipam:
      config:
        - subnet: 172.11.10.0/24
services:
  service-a:
    build: ./serviceA
    networks: 
      base:
    ports:
      - 3000:3000
    entrypoint: npm run start:dev
    volumes:
      - ./serviceA/src:/app/src

  service-b:
    build: ./serviceB
    networks:
      base:
    ports:
      - 3001:3000
    entrypoint: npm run start:dev
    volumes:
      - ./serviceB/src:/app/src

  rabbitmq:
    image: rabbitmq:3.8.2-management-alpine
    networks: 
      base:
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test
    ports:
      - 15672:15672
      - 5672:5672